# Generated by Django 5.2.4 on 2026-02-25 08:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0002_alter_chatmessage_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatsession',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='tokens_used',
            field=models.IntegerField(default=0, help_text='Tokens used for this message'),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='llm_model',
            field=models.CharField(choices=[('gemini-flash-lite', 'Gemini Flash Lite (Fastest)'), ('gemini-1.5-flash', 'Gemini 1.5 Flash (Fast)'), ('gemini-1.5-pro', 'Gemini 1.5 Pro (Balanced)'), ('gpt-4-turbo', 'GPT-4 Turbo (Powerful)'), ('gpt-4-mini', 'GPT-4 Mini (Cost-Effective)')], default='gemini-flash-lite', help_text='Selected LLM for this session', max_length=50),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant'), ('system', 'System')], max_length=20),
        ),
        migrations.AlterField(
            model_name='chatsession',
            name='title',
            field=models.CharField(blank=True, default='New Chat', max_length=255),
        ),
        migrations.AddIndex(
            model_name='chatsession',
            index=models.Index(fields=['user', '-updated_at'], name='Chat_chatse_user_id_61161b_idx'),
        ),
    ]
