# Generated by Django 5.2.4 on 2026-02-26 14:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0003_alter_chatsession_options_chatmessage_tokens_used_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VoiceAgentTrainingData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_input', models.TextField()),
                ('agent_response', models.TextField()),
                ('user_rating', models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='chatsession',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveIndex(
            model_name='chatsession',
            name='Chat_chatse_user_id_61161b_idx',
        ),
        migrations.RemoveField(
            model_name='chatsession',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='chatsession',
            name='llm_model',
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='confidence_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='is_voice_input',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='is_voice_agent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='marked_for_training',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='message_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant'), ('voice_agent', 'Voice Agent'), ('error', 'Error')], max_length=20),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='tokens_used',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='chatsession',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['is_voice_input'], name='Chat_chatme_is_voic_e2e775_idx'),
        ),
        migrations.AddIndex(
            model_name='chatsession',
            index=models.Index(fields=['user', '-created_at'], name='Chat_chatse_user_id_89e2c6_idx'),
        ),
        migrations.AddIndex(
            model_name='chatsession',
            index=models.Index(fields=['is_voice_agent'], name='Chat_chatse_is_voic_699aee_idx'),
        ),
        migrations.AddIndex(
            model_name='chatsession',
            index=models.Index(fields=['marked_for_training'], name='Chat_chatse_marked__1b2658_idx'),
        ),
        migrations.AddField(
            model_name='voiceagenttrainingdata',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Chat.chatsession'),
        ),
        migrations.AddField(
            model_name='voiceagenttrainingdata',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_data', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='voiceagenttrainingdata',
            index=models.Index(fields=['user', '-created_at'], name='Chat_voicea_user_id_cf9a4e_idx'),
        ),
    ]
