# Generated by Django 5.2.4 on 2026-02-26 15:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0004_voiceagenttrainingdata_alter_chatsession_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RateLimitPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.CharField(choices=[('free', 'Free'), ('premium', 'Premium'), ('professional', 'Professional')], max_length=20, unique=True)),
                ('voice_messages_per_month', models.IntegerField(default=10)),
                ('text_messages_per_month', models.IntegerField(default=50)),
                ('api_calls_per_day', models.IntegerField(default=100)),
                ('max_tokens_per_month', models.IntegerField(default=10000)),
                ('requests_per_minute', models.IntegerField(default=10)),
                ('can_use_voice_agent', models.BooleanField(default=True)),
                ('can_use_premium_models', models.BooleanField(default=False)),
                ('can_export_data', models.BooleanField(default=False)),
                ('priority_support', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Rate Limit Policies',
            },
        ),
        migrations.AddField(
            model_name='chatsession',
            name='llm_model',
            field=models.CharField(choices=[('gemini-2.0-flash', 'Gemini 2.0 Flash (Fast)'), ('gemini-1.5-pro', 'Gemini 1.5 Pro (Advanced)'), ('gpt-4-turbo', 'GPT-4 Turbo (Premium)')], default='gemini-2.0-flash', max_length=50),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='voice_tone',
            field=models.CharField(choices=[('neutral', 'Neutral'), ('friendly', 'Friendly'), ('professional', 'Professional'), ('casual', 'Casual'), ('formal', 'Formal'), ('enthusiastic', 'Enthusiastic'), ('empathetic', 'Empathetic')], default='neutral', max_length=50),
        ),
        migrations.CreateModel(
            name='PremiumSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('free', 'Free'), ('trial', 'Trial'), ('active', 'Active'), ('paused', 'Paused'), ('cancelled', 'Cancelled')], default='free', max_length=20)),
                ('tier', models.CharField(choices=[('free', 'Free'), ('premium', 'Premium ($9.99/mo)'), ('professional', 'Professional ($29.99/mo)')], default='free', max_length=20)),
                ('stripe_customer_id', models.CharField(blank=True, max_length=255, null=True)),
                ('stripe_subscription_id', models.CharField(blank=True, max_length=255, null=True)),
                ('stripe_payment_method_id', models.CharField(blank=True, max_length=255, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('trial_ends_at', models.DateTimeField(blank=True, null=True)),
                ('current_period_end', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('next_billing_date', models.DateTimeField(blank=True, null=True)),
                ('auto_renew', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='premium_subscription', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Premium Subscriptions',
            },
        ),
        migrations.CreateModel(
            name='UsageTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.CharField(choices=[('free', 'Free Tier'), ('premium', 'Premium'), ('professional', 'Professional')], default='free', max_length=20)),
                ('voice_messages_used', models.IntegerField(default=0)),
                ('text_messages_used', models.IntegerField(default=0)),
                ('api_calls_used', models.IntegerField(default=0)),
                ('tokens_used', models.IntegerField(default=0)),
                ('voice_messages_limit', models.IntegerField(default=10)),
                ('text_messages_limit', models.IntegerField(default=50)),
                ('api_calls_limit', models.IntegerField(default=100)),
                ('tokens_limit', models.IntegerField(default=10000)),
                ('last_reset', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='usage_tracking', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Usage Tracking',
            },
        ),
        migrations.CreateModel(
            name='VoiceToneCustomization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tone', models.CharField(choices=[('neutral', 'Neutral'), ('friendly', 'Friendly'), ('professional', 'Professional'), ('casual', 'Casual'), ('formal', 'Formal'), ('enthusiastic', 'Enthusiastic'), ('empathetic', 'Empathetic')], default='neutral', max_length=50)),
                ('speaking_rate', models.FloatField(default=1.0)),
                ('pitch', models.FloatField(default=1.0)),
                ('custom_system_prompt', models.TextField(blank=True, help_text='Custom system prompt for voice agent')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='voice_tone_customization', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Voice Tone Customizations',
            },
        ),
    ]
